"""Add gift claim fields

Revision ID: 3420f60f3571
Revises: 94d2aa96f567
Create Date: 2026-06-28 20:08:19.201646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3420f60f3571'
down_revision: Union[str, Sequence[str], None] = '94d2aa96f567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_orders', sa.Column('recipient_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('gift_orders', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lifetime_subscriptions', sa.Column('delivery_address_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lifetime_subscriptions', 'delivery_address_override')
    op.drop_column('gift_orders', 'claimed_at')
    op.drop_column('gift_orders', 'recipient_address')
    # ### end Alembic commands ###
