"""Add is_private to community groups

Revision ID: 37eb44aa8885
Revises: dd0d829a2799
Create Date: 2026-06-24 02:42:48.999066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37eb44aa8885'
down_revision: Union[str, Sequence[str], None] = 'dd0d829a2799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('community_groups', sa.Column('is_private', sa.Boolean(), nullable=True))
    
    # Update existing rows to default False
    op.execute("UPDATE community_groups SET is_private = FALSE")
    
    # Alter column to be NOT NULL
    op.alter_column('community_groups', 'is_private', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_groups', 'is_private')
    # ### end Alembic commands ###
