"""Drop per_household_share from community_orders

Revision ID: 94d2aa96f567
Revises: 37eb44aa8885
Create Date: 2026-06-24 03:27:13.656290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d2aa96f567'
down_revision: Union[str, Sequence[str], None] = '37eb44aa8885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_orders', 'per_household_share')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_orders', sa.Column('per_household_share', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
