"""Add rejection_reason to LegacyActivation

Revision ID: dd0d829a2799
Revises: 4d4413508d1d
Create Date: 2026-06-22 15:09:24.257851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd0d829a2799'
down_revision: Union[str, Sequence[str], None] = '4d4413508d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legacy_activations', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.drop_column('product_substitutes', 'created_at')
    op.drop_column('product_substitutes', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_substitutes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('product_substitutes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('legacy_activations', 'rejection_reason')
    # ### end Alembic commands ###
