"""add recipient_household_id

Revision ID: fe9f371e783b
Revises: 3420f60f3571
Create Date: 2026-06-28 23:08:21.136822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9f371e783b'
down_revision: Union[str, Sequence[str], None] = '3420f60f3571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_orders', sa.Column('recipient_household_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_gift_orders_recipient_household_id'), 'gift_orders', ['recipient_household_id'], unique=False)
    op.create_foreign_key(None, 'gift_orders', 'households', ['recipient_household_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gift_orders', type_='foreignkey')
    op.drop_index(op.f('ix_gift_orders_recipient_household_id'), table_name='gift_orders')
    op.drop_column('gift_orders', 'recipient_household_id')
    # ### end Alembic commands ###
